version: 0.0
os: linux
files:
  - source: /
    destination: /home/azureuser/devops
hooks:
    AfterInstall:
       - location: scripts/copy-files.sh
         timeout: 300
         runas: azureuser
    ApplicationStart:
       - location: scripts/run-ansible-playbook.sh
         timeout: 3600
         runas: azureuser

    
       
