# this file must be under /etc/kubernetes/aws.yml
# for the master node
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  serviceSubnet: 10.100.0.0/16
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    cloud-provider: aws
controllerManager:
  extraArgs:
    cloud-provider: aws
clusterName: kubernetes
# controlPlaneEndpoint: class-load-balancer-505618943.us-west-2.elb.amazonaws.com # this the dns name of the load balancer
