# this file must be under /etc/kubernetes/aws.yml
# for the master node
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  serviceSubnet: "10.100.0.0/16"
  podSubnet: "10.244.0.0/16"
clusterName: kubernetes
# controlPlaneEndpoint: classic-load-balancer-833162346.us-west-2.elb.amazonaws.com
# apiServer:
#   extraArgs:
#     cloud-provider: aws
# controllerManager:
#   extraArgs:
#     cloud-provider: aws