# this file must be under /etc/kubernetes/aws.yml
# for the master node
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: external
clusterName: kubernetes
controlPlaneEndpoint: "ip-10-10-1-133.us-west-2.compute.internal:6443"
controllerManager:
  extraArgs:
    cloud-provider: external
kubernetesVersion: v1.22.2 # can use "stable"
networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.100.0.0/16"
  podSubnet: "10.244.0.0/16"
  
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: ip-10-10-1-186.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: external

    
# apiVersion: kubeadm.k8s.io/v1beta2
# kind: ClusterConfiguration
# networking:
#   podSubnet: 192.168.0.0/16
#   serviceSubnet: 10.96.0.0/12
# clusterName: kubernetes
# controlPlaneEndpoint: classic-load-balancer-833162346.us-west-2.elb.amazonaws.com
# apiServer:
#   extraArgs:
#     cloud-provider: aws
# controllerManager:
#   extraArgs:
#     cloud-provider: aws