apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "1nr5hv.lwmyb9pz5bkqbd3p"
    apiServerEndpoint: "10.10.1.6:6443" # controlplaneendpoint: 6443
    # the control
    caCertHashes:
      - "sha256:35cbb28670a18c275919f3bb210d9edb4d8a243b9de54463b75b8a18a67f4400"
nodeRegistration:
  name: ip-10-10-1-16.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws