
# create this file under /etc/kubernetes on your worker node
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "jtapn5.z1rwhatjelzpzsjp"
    apiServerEndpoint: "176.24.1.234:6443"
    caCertHashes:
      - "sha256:5e3319063b01646d4f31bd5720941e71f6f280e6e84962f8bde2dbc838833474"
nodeRegistration:
  name: ip-176-24-1-134.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws