apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "1egdvy.cnkm4u65vaijwu1r"
    apiServerEndpoint: "10.10.1.40:6443 "
    caCertHashes:
      - "sha256:b0546d2e377eb4790ae983bfb77d07dfed966aafbf9c0a3207782e169d6a6251"
nodeRegistration:
  name: ip-10-10-1-244.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws