# create this file under /etc/kubernetes on your worker node
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "p7p5za.y51etnpo6u2d6f4j"
    apiServerEndpoint: "10.10.1.33:6443"
    caCertHashes: ["sha256:79fdb48d68d68a07fd6308eb8964c09dca54e6c9d0fcdc3d5dabb0b9b3d11197"]
nodeRegistration:
  name: ip-10-10-1-221.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: external