apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "a66880.23sgjn8hgqnhrsia"
    apiServerEndpoint: "10.10.1.59:6443"
    caCertHashes:
      - "sha256:3a56028ef3155f5f52e4844ab6e492ecf2638fd53a72a56a5b0a77e9405a7c16"
nodeRegistration:
  name: ip-10-10-1-121.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws