# create this file under /etc/kubernetes on your worker node
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "hqu9f5.fmzb8zv3jdno2e19"
    apiServerEndpoint: "ip-10-10-1-133.us-west-2.compute.internal:6443"
    caCertHashes: ["sha256:117496e5bfc98460ee7a206b044b608e3c1f4b102ca34206adc0b840a425162d"]
nodeRegistration:
  name: ip-10-10-1-113.us-west-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: external