- name: build docker image and push it to dockr hub
  hosts: local
  become: yes 
  become_user: azureuser
  

  tasks:
  - name: build image
    command: docker build -t azure-reactjs .
    args:
       chdir: /home/azureuser/devops/nginx

  - name: tag the image
    command: docker tag azure-reactjs abdelalidocker/azure-reactjs:latest


  - name: push the built image to dockerhub
    command: docker push abdelalidocker/azure-reactjs:latest


  - name: delete the built image and the taged one
    command: docker rmi azure-reactjs abdelalidocker/azure-reactjs:latest